### PR TITLE
Newsweek clone

### PR DESCRIPTION
**Pull request by elyor-doniyorov**
This is the last we did. We fixed the last code review issues such as
1. space between nav and content in Tablet and Mobile screen,
2. We reduced CSS code instead we used Bootstrap 
3. Positioning of footer items and Logo change
4. Positioning of Opinion section
5. In Tablet size "In the magazine 4 sections are in a row ", "U.S smaller sections text are not missing", "Subscribe and Newsweek sections  are not centered"
6. In Mobile size fixed footer images, main newspaper section, In the magazine section images, latest news and more stories text position, opinion section and space between nav and content

### CODE REVIEW

**Comment by billodiallo** [comment]
https://github.com/billodiallo/newsweek2020/issues/3 please check the issue in regard to last comment of the review .
We don't know how we lost them  beacause the reviewer told us to change the name of the branch..
Maybe we misunderstood  him.

 We fixed all mandatory feedback for milestone 3 .
THANK you in advance.

**Review by BrittanyBlake — CHANGES_REQUESTED** [review]
### Status: Changes Required ♻️ 
****
### Hi @EL28DEV and @billodiallo! 👋 
Great job working on the requested changes!👏 👏 👏  There are just a few issues that need to be resolved before you can move on: ⬇️ 
****
### GENERAL
- [ ] You are using a lot of css styling that can be done with bootstrap classes. Please take a look at this [cheat sheet](https://hackerthemes.com/bootstrap-cheatsheet/) and see what rules you can replace with bootstrap classes. 

### DESKTOP

- [ ] The text on the subscribe section is hidden by the article images. 
Your clone 👇🏾 
Screen Shot 2021-01-30 at 11 12 19 PM

The original page 👇🏾 
Screen Shot 2021-01-30 at 11 12 47 PM

### TABLET

- [ ] Your nav bar is covering the section names.
Your clone 👇🏾 
Screen Shot 2021-01-30 at 11 16 32 PM

The original page 👇🏾 
Screen Shot 2021-01-30 at 11 16 55 PM

- [ ] The articles in the opinion section shouldn't be centered.
Your clone 👇🏾 
Screen Shot 2021-01-30 at 11 18 33 PM
The original page 👇🏾 
Screen Shot 2021-01-30 at 11 18 49 PM

- [ ] Your in the magazine section should have 4 articles in a row. Yours currently has 1 in one row, 3 in the next, and 4 in the last row.
Your clone 👇🏾 
Screen Shot 2021-01-30 at 11 21 03 PM
The original page 👇🏾 
Screen Shot 2021-01-30 at 11 21 26 PM

- [ ] In the Main newspaper sections (US, World, etc.), your 3 smaller images are missing the text.
your clone 👇🏾 
Screen Shot 2021-01-30 at 11 23 15 PM
The original page 👇🏾 
Screen Shot 2021-01-30 at 11 23 34 PM

- [ ] Your Subscribe and Newsletter sections should have the image on the left and the text on the right, but yours are centered.
Your clone 👇🏾 

Screen Shot 2021-01-30 at 11 25 26 PM
Screen Shot 2021-01-30 at 11 25 51 PM

The original page 👇🏾 
Screen Shot 2021-01-30 at 11 26 28 PM

- [ ] The logo, copyright text, and social media icons should be in one row. 
Your clone 👇🏾 
Screen Shot 2021-01-30 at 11 27 25 PM

The original page 👇🏾 
Screen Shot 2021-01-30 at 11 27 38 PM

### MOBILE

- [ ] In the footer, the magazine images should overlap
Your clone 👇🏾 
Screen Shot 2021-01-30 at 11 28 41 PM

The original page 👇🏾 
Screen Shot 2021-01-30 at 11 28 59 PM

- [ ] In the Main newspaper sections (US, World, etc.), your 3 smaller articles should not be centered
Your clone 👇🏾 
Screen Shot 2021-01-30 at 11 30 19 PM

The original page 👇🏾 
Screen Shot 2021-01-30 at 11 30 43 PM

- [ ] In your In The Magazine section all of the images should be the same size, except the first which should be larger than the others. 
Your clone 👇🏾 
Screen Shot 2021-01-30 at 11 32 24 PM
Screen Shot 2021-01-30 at 11 32 36 PM

The original page 👇🏾 

Screen Shot 2021-01-30 at 11 33 02 PM
Screen Shot 2021-01-30 at 11 33 16 PM

- [ ] In the Latest News and More Stories sections, the text should not wrap under the images
Your clone 👇🏾 
Screen Shot 2021-01-30 at 11 34 39 PM
Screen Shot 2021-01-30 at 11 35 49 PM

The original page 👇🏾 
Screen Shot 2021-01-30 at 11 36 00 PM
Screen Shot 2021-01-30 at 11 36 21 PM

- [ ] Your opinion section should be left aligned, not centered.
Your clone 👇🏾 
Screen Shot 2021-01-30 at 11 36 58 PM

The original page 👇🏾 
Screen Shot 2021-01-30 at 11 37 41 PM

- [ ] Your nav bar is blocking a bit of the top story section name 
your clone 👇🏾 
Screen Shot 2021-01-30 at 11 38 36 PM
The original page 👇🏾 
Screen Shot 2021-01-30 at 11 38 50 PM



****
Good Luck and Happy Coding 🍀 👩🏾‍💻

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Brittany Blake)._

**Comment by billodiallo** [comment]
changes done .

**Review by BrittanyBlake — CHANGES_REQUESTED** [review]
### Status: Changes Required  🏗️ 🔨 
****
### Hello @EL28DEV   👋 
You are making great progress with this project! 👍 You are almost done! 💪 Great job applying the feedback you have received🎖️ 🌟 There are just a few small issues that need to be resolved before you can move on: ⬇️ 
****
### TABLET

- [ ] The articles in the opinion page are still centered. The Image should be on the left with the text on the right.
Your clone 👇🏾 
Screen Shot 2021-01-31 at 11 38 09 AM
The original page 👇🏾 
Screen Shot 2021-01-31 at 11 39 07 AM

- [ ] Your Main newspaper sections still does not look like the original. The text for the 3 smaller images is missing. 
Your clone 👇🏾 
Screen Shot 2021-01-31 at 11 43 26 AM

The original page 👇🏾 
Screen Shot 2021-01-31 at 11 43 53 AM

- [ ] Your subscribe and newsletter sections should not be centered. The images should be on the left and the text on the right. 
Your clone 👇🏾 
Screen Shot 2021-01-31 at 11 44 46 AM
Screen Shot 2021-01-31 at 11 44 58 AM

The original page 👇🏾 
Screen Shot 2021-01-31 at 11 45 26 AM



****
### Kindly make the required changes and resubmit for a new code review once you are ready 🙏


Good Luck and Happy Coding 🍀 👩🏾‍💻

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Brittany Blake)._

**Comment by elyor-doniyorov** [comment]
Hello Brittany, thank you for your feedbacks. I don't see such things on my screen. They are all on their place

**Comment by elyor-doniyorov** [comment]
I wrote you on slack 8 hours ago. Could you help us to understand what are missing in our project. We can show you ours. Kindly ask you to re check or show us the issue on zoom if you are available please

**Comment by elyor-doniyorov** [comment]
Screenshot (278)
 This is the screenshot of the original page that Microverse gave us. Subscribe section should be similar to this. That's why we did not change it.  Added tablet versions of Opinion and Newspaper sections. Kindly ask you to re-check the original website and let us move on. We have to start the next week's Capstone project.

**Comment by billodiallo** [comment]
@BrittanyBlake 
We fixed the small error you said for subscribe.
kindly check again , it changed

**Comment by elyor-doniyorov** [comment]
Hi Brittany, we are sorry that you were right. The problem with us was that we did not inspect the website so that we did not see our mistake. But we fixed the issues you asked now

**Review by BrittanyBlake — APPROVED** [review]
### Status: Approved ✅ 
****
### Hi Team! 👋 
### Great job implementing the requested changes!! 🎖️ It's a 👍 from me! Go ahead and merge this pull request and keep up the good work 😄
****


 Good Luck and Happy Coding! 🍀 👩🏾‍💻

**Pull request merged**
